/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.OpcionesUser.Form_ElegirUsuario;
import Vista.OpcionesUser.Form_NuevoUs;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class Form_ElegirInicio extends javax.swing.JFrame {

    /**
     * Creates new form Form_ElegirInicio
     */
    public Form_ElegirInicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbtn_NewGame = new javax.swing.JButton();
        Jbtn_Load = new javax.swing.JButton();
        jbtn_return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Select Game");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 310, 80));

        Jbtn_NewGame.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_NewGame.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        Jbtn_NewGame.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_NewGame.setText("New Game");
        Jbtn_NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_NewGameActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_NewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        Jbtn_Load.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Load.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        Jbtn_Load.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Load.setText("Load Game");
        Jbtn_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LoadActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        jbtn_return.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_return.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jbtn_return.setForeground(new java.awt.Color(255, 255, 102));
        jbtn_return.setText("Return");
        jbtn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_NewGameActionPerformed
        Form_NuevoUs n = new Form_NuevoUs();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_NewGameActionPerformed

    private void Jbtn_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LoadActionPerformed
        Form_ElegirUsuario eu = new Form_ElegirUsuario();
        eu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Jbtn_LoadActionPerformed

    private void jbtn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_returnActionPerformed
        MenuPrincipal m = new MenuPrincipal();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_returnActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_ElegirInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_ElegirInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_ElegirInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_ElegirInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_ElegirInicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Load;
    private javax.swing.JButton Jbtn_NewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtn_return;
    // End of variables declaration//GEN-END:variables
}
