
package Vista;

import Controlador.Batalla;
import Controlador.Encuentro;
import Controlador.ProgresionMapa;
import Modelo.Heroe;

/**
 *
 * @author Panky
 */
public class Form_Pelea extends javax.swing.JFrame {

    /**
     * Creates new form Form_Pelea
     */
    private ProgresionMapa pro;
    private Heroe heroeDelJuego; // Para guardar la referencia del héroe

    // Constructor modificado para recibir el héroe
    public Form_Pelea(Heroe heroe) {
        initComponents(); // Inicializa componentes de Swing
        this.heroeDelJuego = heroe;
        Jbtn_Continuar.setVisible(false);
        inicializarJuego(); // Nuevo método para configurar la lógica del juego
    }
    private void inicializarJuego() {
        // Debes inicializar tus objetos Encuentro y Batalla
        Encuentro encuentro = new Encuentro(); // Asumiendo un constructor por defecto
        Batalla batalla = new Batalla();       // Asumiendo un constructor por defecto

        // Inicializar ProgresionMapa con los objetos
        // Puedes iniciar el piso en 1 (o el que corresponda al progreso guardado del héroe)
        pro = new ProgresionMapa(1, encuentro, batalla, heroeDelJuego);
        
        // 🔹 Asocia el botón "Continuar" del formulario (si existe) al controlador
        // progresion.setBotonContinuar(btnContinuar); 
        
        // Inicia el primer encuentro inmediatamente
        pro.iniciarEncuentro(heroeDelJuego);
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Jbtn_Ataque = new javax.swing.JButton();
        Jbtn_SpAtaque = new javax.swing.JButton();
        Jbtn_Guardia = new javax.swing.JButton();
        Jbtn_Salir = new javax.swing.JButton();
        Jbtn_Continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        Jbtn_Ataque.setText("Attack");
        Jbtn_Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_AtaqueActionPerformed(evt);
            }
        });

        Jbtn_SpAtaque.setText("Special Attack");
        Jbtn_SpAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_SpAtaqueActionPerformed(evt);
            }
        });

        Jbtn_Guardia.setText("Guard");
        Jbtn_Guardia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_GuardiaActionPerformed(evt);
            }
        });

        Jbtn_Salir.setText("Exit");
        Jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Jbtn_Ataque))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jbtn_Guardia)
                            .addComponent(Jbtn_Salir)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Jbtn_SpAtaque)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Jbtn_Ataque)
                .addGap(27, 27, 27)
                .addComponent(Jbtn_SpAtaque)
                .addGap(31, 31, 31)
                .addComponent(Jbtn_Guardia)
                .addGap(31, 31, 31)
                .addComponent(Jbtn_Salir)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Jbtn_Continuar.setText("Continue");
        Jbtn_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addComponent(Jbtn_Continuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Jbtn_Continuar)
                .addGap(441, 441, 441)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_AtaqueActionPerformed
         
        pro.turnoHeroe(1);   // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_AtaqueActionPerformed

    private void Jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_SalirActionPerformed
        MainMenu M = new MainMenu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_SalirActionPerformed

    private void Jbtn_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_ContinuarActionPerformed

    private void Jbtn_SpAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_SpAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_SpAtaqueActionPerformed

    private void Jbtn_GuardiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_GuardiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_GuardiaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pelea().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Ataque;
    private javax.swing.JButton Jbtn_Continuar;
    private javax.swing.JButton Jbtn_Guardia;
    private javax.swing.JButton Jbtn_Salir;
    private javax.swing.JButton Jbtn_SpAtaque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    
}
