/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Heroe;
import Modelo.HeroeDao;
import Modelo.Usuario;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class Form_SeleccionarHeroe extends javax.swing.JFrame {

    /**
     * Creates new form Form_SeleccionarHeroe
     */
    public Form_SeleccionarHeroe() {
        initComponents();       
    }

    private Usuario usuarioActual; //objeto usuario completo de la db

    public Form_SeleccionarHeroe(Usuario usuario) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
        this.usuarioActual = usuario;

        this.setTitle("Seleccionar Héroe para: " + usuario.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbtn_StartR = new javax.swing.JButton();
        Jbtn_StartB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Select a Hero");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 340, 80));

        Jbtn_StartR.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_StartR.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_StartR.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_StartR.setText("Start Robin");
        Jbtn_StartR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_StartRActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_StartR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 270, -1));

        Jbtn_StartB.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_StartB.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_StartB.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_StartB.setText("Start Batman");
        Jbtn_StartB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_StartBActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_StartB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPersonajes/BotonBatman.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 360, 400));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPersonajes/BotonRobin.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 340, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_StartBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_StartBActionPerformed
        bd.Conexion con = new bd.Conexion();
        Connection cnx = con.obtenerConexion();

        if (cnx != null) {
            HeroeDao daoHeroe = new HeroeDao(cnx);
            Heroe heroeElegido = daoHeroe.obtenerHeroePorNombre("Batman", usuarioActual);

            // asociación al usuario que recibimos.
            if (heroeElegido != null) {
                heroeElegido.setUsuarioAsociado(this.usuarioActual); 
            }

            try {
                cnx.close();
            } catch (SQLException e) {
                System.out.println("Error al cerrar conexion: " + e.getMessage());
            }

            if (heroeElegido != null) {
                this.dispose();
                Form_Pelea p = new Form_Pelea(heroeElegido);
                p.setVisible(true);
            } else {
                System.out.println("Error: No se pudo obtener el heroe 'Batman'");
            }
        } else {
            System.out.println("Error, no se pudo establecer la conexion con la base de datos.");
        }
        this.dispose(); 
    }//GEN-LAST:event_Jbtn_StartBActionPerformed

    private void Jbtn_StartRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_StartRActionPerformed
        bd.Conexion con = new bd.Conexion();
        Connection cnx = con.obtenerConexion();

        if (cnx != null) {
            HeroeDao daoHeroe = new HeroeDao(cnx);
            Heroe heroeElegido = daoHeroe.obtenerHeroePorNombre("Robin", usuarioActual);

            // asociación al Usuario que recibimos.
            if (heroeElegido != null) {
                heroeElegido.setUsuarioAsociado(this.usuarioActual); 
            }

            try {
                cnx.close();
            } catch (SQLException e) {
                System.out.println("Error al cerrar conexion: " + e.getMessage());
            }

            if (heroeElegido != null) {
                this.dispose();
                Form_Pelea p = new Form_Pelea(heroeElegido);
                p.setVisible(true);
            } else {
                System.out.println("Error: No se pudo obtener el heroe 'Robin'");
            }
        } else {
            System.out.println("Error, no se pudo establecer la conexion con la base de datos.");
        }
        this.dispose();
    }//GEN-LAST:event_Jbtn_StartRActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_SeleccionarHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_SeleccionarHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_SeleccionarHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_SeleccionarHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_SeleccionarHeroe().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_StartB;
    private javax.swing.JButton Jbtn_StartR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
