package Vista;

import Vista.MenuPrincipal;
import Vista.OpcionesPersonaje.Form_OpcionesPj;
import Vista.OpcionesUser.Form_OpcionesUser;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class Form_Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Form_Opciones
     */
    public Form_Opciones() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbnt_Usuario = new javax.swing.JButton();
        Jbtn_Personaje = new javax.swing.JButton();
        Jbtn_VolverMP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Options");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        Jbnt_Usuario.setBackground(new java.awt.Color(0, 0, 0));
        Jbnt_Usuario.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbnt_Usuario.setForeground(new java.awt.Color(255, 255, 102));
        Jbnt_Usuario.setText("User");
        Jbnt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbnt_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Jbnt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 260, 70));

        Jbtn_Personaje.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Personaje.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_Personaje.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Personaje.setText("Villains");
        Jbtn_Personaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_PersonajeActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 260, 70));

        Jbtn_VolverMP.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_VolverMP.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_VolverMP.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_VolverMP.setText("Return Menu");
        Jbtn_VolverMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverMPActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_VolverMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 260, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        jLabel1.setText("3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_VolverMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverMPActionPerformed
        MenuPrincipal m = new MenuPrincipal();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverMPActionPerformed

    private void Jbtn_PersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_PersonajeActionPerformed
        Form_OpcionesPj pj = new Form_OpcionesPj();
        pj.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Jbtn_PersonajeActionPerformed

    private void Jbnt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbnt_UsuarioActionPerformed
        Form_OpcionesUser opU = new Form_OpcionesUser();
        opU.setVisible(true);
        this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_Jbnt_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Opciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbnt_Usuario;
    private javax.swing.JButton Jbtn_Personaje;
    private javax.swing.JButton Jbtn_VolverMP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
