/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Sonidos.Sonido;
import javax.sound.sampled.Clip;

/**
 *
 * @author Panky
 */
public class MainMenu extends javax.swing.JFrame {
    
    private Clip musicaFondo;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

        musicaFondo = Sonido.reproducirLoop("Fondo.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbnt_Start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jbtn_Opciones = new javax.swing.JButton();
        Jbnt_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbnt_Start.setBackground(new java.awt.Color(0, 0, 0));
        Jbnt_Start.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbnt_Start.setForeground(new java.awt.Color(255, 255, 102));
        Jbnt_Start.setText("Start");
        Jbnt_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbnt_StartActionPerformed(evt);
            }
        });
        getContentPane().add(Jbnt_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, 60));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Batman Rogue");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 340, 80));

        Jbtn_Opciones.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Opciones.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_Opciones.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Opciones.setText("Options");
        Jbtn_Opciones.setToolTipText("");
        Jbtn_Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_OpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 130, 60));

        Jbnt_Salir.setBackground(new java.awt.Color(0, 0, 0));
        Jbnt_Salir.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbnt_Salir.setForeground(new java.awt.Color(255, 255, 102));
        Jbnt_Salir.setText("Exit");
        Jbnt_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jbnt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbnt_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Jbnt_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbnt_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbnt_StartActionPerformed
        Sonido.reproducir("Transicion.wav");
        this.dispose();
        Form_Pelea p = new Form_Pelea();
        p.setVisible(true);
    }//GEN-LAST:event_Jbnt_StartActionPerformed

    private void Jbtn_OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_OpcionesActionPerformed
        Form_Opciones op = new Form_Opciones();
        op.setVisible(true);
        Sonido.reproducir("Transicion.wav");
        this.dispose();
        
    }//GEN-LAST:event_Jbtn_OpcionesActionPerformed

    private void Jbnt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbnt_SalirActionPerformed
        Sonido.reproducir("Transicion.wav");
        System.exit(0);
    }//GEN-LAST:event_Jbnt_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbnt_Salir;
    private javax.swing.JButton Jbnt_Start;
    private javax.swing.JButton Jbtn_Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
