/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Sonidos.Sonido;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Clip musicaFondo;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
        Sonido.reproducirLoop("Fondo.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbtn_Start = new javax.swing.JButton();
        Jbtn_Opciones = new javax.swing.JButton();
        Jbtn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Batman Rogue");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 340, 90));

        Jbtn_Start.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Start.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_Start.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Start.setText("Start");
        Jbtn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_StartActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 200, 70));

        Jbtn_Opciones.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Opciones.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_Opciones.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Opciones.setText("Options");
        Jbtn_Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_OpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 200, 70));

        Jbtn_Exit.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Exit.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        Jbtn_Exit.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Exit.setText("Exit");
        Jbtn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_StartActionPerformed
        Form_ElegirInicio ei = new Form_ElegirInicio();
        ei.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_StartActionPerformed

    private void Jbtn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ExitActionPerformed
        Sonido.detenerLoop();
        System.exit(0);
    }//GEN-LAST:event_Jbtn_ExitActionPerformed

    private void Jbtn_OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_OpcionesActionPerformed
        Form_Opciones op = new Form_Opciones();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_OpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Exit;
    private javax.swing.JButton Jbtn_Opciones;
    private javax.swing.JButton Jbtn_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
