/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesUser;

import Controlador.Encuentro;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_EliminarUs extends javax.swing.JFrame {

    /**
     * Creates new form Form_EliminarUs
     */
    public Form_EliminarUs() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Jtxt_Nick = new javax.swing.JTextField();
        Jbtn_Limpiar = new javax.swing.JButton();
        Jbtn_Eliminar = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nick:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 60, 30));
        getContentPane().add(Jtxt_Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 380, 30));

        Jbtn_Limpiar.setText("Clear");
        Jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        Jbtn_Eliminar.setText("Delete");
        Jbtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Delete User");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUsuario.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LimpiarActionPerformed
        this.Jtxt_Nick.setText("");
        this.Jtxt_Nick.requestFocus();
        
    }//GEN-LAST:event_Jbtn_LimpiarActionPerformed

    private void Jbtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_EliminarActionPerformed
        // Eliminar al usuario de la lista!
        
        String nombre = this.Jtxt_Nick.getText();
        
        Encuentro encuentro = new Encuentro();
        
        if (encuentro.eliminarUsuario(nombre)) {
            JOptionPane.showMessageDialog(null, "Usuario elimnado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario no encontrado o fallo base datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Jbtn_EliminarActionPerformed

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_OpcionesUser op = new Form_OpcionesUser();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_EliminarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_EliminarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_EliminarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_EliminarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_EliminarUs().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Eliminar;
    private javax.swing.JButton Jbtn_Limpiar;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JTextField Jtxt_Nick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
