/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesUser;

import Controlador.Encuentro;
import Modelo.Usuario;
import Vista.Form_SeleccionarHeroe;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_ElegirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Form_ListarUs
     */
    public Form_ElegirUsuario() {
        initComponents();
        cargarUsuariosComboBox();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbtn_Volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbo_usuarios = new javax.swing.JComboBox<>();
        jbtn_aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("User:");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, 50));

        jcbo_usuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcbo_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbo_usuarios);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 160, 50));

        jbtn_aceptar.setText("Accept");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 90, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Select User");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUsuario.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_OpcionesUser opU = new Form_OpcionesUser();
        opU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        // TODO add your handling code here:

        if (jcbo_usuarios.getSelectedItem() != null) {

            // obtener el nombre 
            String nombreSeleccionado = (String) jcbo_usuarios.getSelectedItem();

            // buscar el objeto Usuario completo en la BD (usando el controlador)
            Encuentro encuentro = new Encuentro(); // O usar una instancia si ya existe
            Usuario usuarioSeleccionado = encuentro.buscarPorNombreUsuario(nombreSeleccionado);

            if (usuarioSeleccionado != null) {
                this.dispose();
                Form_SeleccionarHeroe seleccionarHeroe = new Form_SeleccionarHeroe(usuarioSeleccionado);
                seleccionarHeroe.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Error al cargar los datos del usuario.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario antes de continuar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    private void cargarUsuariosComboBox() {

        jcbo_usuarios.removeAllItems();

        Encuentro encuentro = new Encuentro();
        List<Usuario> listaUsuarios = encuentro.listarUsuarios();

        for (Usuario usuario : listaUsuarios) {
            jcbo_usuarios.addItem(usuario.getNombreUsuario());
        }

        if (!listaUsuarios.isEmpty()) {
            jcbo_usuarios.setSelectedIndex(0);
        }

    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_ListarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_ListarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_ListarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_ListarUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_ListarUs().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JComboBox<String> jcbo_usuarios;
    // End of variables declaration//GEN-END:variables
}
