/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesUser;

import Controlador.Encuentro;
import Modelo.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_UpdateUs extends javax.swing.JFrame {

    /**
     * Creates new form Form_UpdateUs
     */
    public Form_UpdateUs() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_genero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_buscarNombre = new javax.swing.JTextField();
        Jtxt_nombreActualizar = new javax.swing.JTextField();
        Jtxt_edadActualizar = new javax.swing.JTextField();
        jbtn_search = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrbtn_hombreActualizar = new javax.swing.JRadioButton();
        jrbtn_mujerActualizar = new javax.swing.JRadioButton();
        jrbtn_otroActualizar = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Jbtn_Actualizar = new javax.swing.JButton();
        Jbtn_Limpiar = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Gender:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 110, 30));

        jLabel3.setText("Nickname:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 30));

        jLabel4.setText("Age:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 110, 30));
        getContentPane().add(jtxt_buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 350, 30));
        getContentPane().add(Jtxt_nombreActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 350, 30));
        getContentPane().add(Jtxt_edadActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, 30));

        jbtn_search.setText("Search");
        jbtn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 80, 30));

        jbg_genero.add(jrbtn_hombreActualizar);
        jrbtn_hombreActualizar.setText("Male");

        jbg_genero.add(jrbtn_mujerActualizar);
        jrbtn_mujerActualizar.setText("Female");

        jbg_genero.add(jrbtn_otroActualizar);
        jrbtn_otroActualizar.setText("Other");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbtn_hombreActualizar)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_mujerActualizar)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_otroActualizar)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrbtn_hombreActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jrbtn_mujerActualizar)
                .addComponent(jrbtn_otroActualizar))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 210, 30));

        jLabel5.setText("Search Nickname:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 110, 30));

        Jbtn_Actualizar.setText("Update");
        Jbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        Jbtn_Limpiar.setText("Clear");
        Jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Update User");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUsuario.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_OpcionesUser op = new Form_OpcionesUser();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

    private void Jbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ActualizarActionPerformed
        // Actualizar los datos del Usuario (nombre,genero,edad)
        String nombreActualizado = this.Jtxt_nombreActualizar.getText().trim();
        String nombreOriginal = this.jtxt_buscarNombre.getText().trim();
        
        //comprobar que la edad sea valida
        int edad;
        try {
            edad = Integer.parseInt(this.Jtxt_edadActualizar.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"La edad debe ser un numero entero valido","ERROR",0);
            return;//detiene la ejecucion si hay error
        }
        
        //obtener genero de los jrbtn
        String genero = "";
        if (this.jrbtn_hombreActualizar.isSelected()) {
            genero = "Masculino";
        }else if (this.jrbtn_mujerActualizar.isSelected()) {
            genero = "Femenino";
        }else if (this.jrbtn_otroActualizar.isSelected()) {
            genero = "Otro";
        }
        
        if (genero.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debe seleccionar un genero","ERROR",0);
            return;
        }
        
        
        Encuentro encuentro = new Encuentro();
        
        int puntaje = encuentro.obtenerPuntaje(nombreOriginal);
        if (puntaje == -1) {
            JOptionPane.showMessageDialog(null,"No se encontro puntaje del usuario original", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        Usuario usuarioActualizado = new Usuario(nombreActualizado, genero, edad, puntaje);
        
        
        if (encuentro.actualizarUsuario(usuarioActualizado, nombreOriginal)) {
            JOptionPane.showMessageDialog(null,"Usuario " + nombreActualizado + " actualizado con exito!","Actualizacion exitosa!",1);
            
            this.jtxt_buscarNombre.setText("");
            this.Jtxt_nombreActualizar.setText("");
            this.Jtxt_edadActualizar.setText("");
            this.jbg_genero.clearSelection();
            this.jtxt_buscarNombre.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null,"Error al actualizar el usuario, revisa bd o si el usuario existe", "ERROR",0);
        }
        
    }//GEN-LAST:event_Jbtn_ActualizarActionPerformed

    private void Jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LimpiarActionPerformed
        this.jtxt_buscarNombre.setText("");
        this.Jtxt_nombreActualizar.setText("");
        this.Jtxt_edadActualizar.setText("");
        this.jbg_genero.clearSelection();
        this.jtxt_buscarNombre.requestFocus();

    }//GEN-LAST:event_Jbtn_LimpiarActionPerformed

    private void jbtn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_searchActionPerformed
        // Buscar al usuario y rellene lo demas
        String nombre = this.jtxt_buscarNombre.getText().trim();
        Encuentro encuentro = new Encuentro();

        Usuario usu = encuentro.buscarPorNombreUsuario(nombre);

        if (usu != null) { // si se encuentra el usuario

            this.Jtxt_nombreActualizar.setText(usu.getNombreUsuario()); //rellenando los campos de jtxt 
            this.Jtxt_edadActualizar.setText(String.valueOf(usu.getEdad()));
            
            String genero = usu.getGenero();
            
            //ahora se selecciona el acorde al usuario
            if ("Masculino".equalsIgnoreCase(genero)|| "Male".equalsIgnoreCase(genero)) { //vverifica si en la bd esta guardado como Masculino o Male(OpenEnglish nunca se sabe)
                this.jrbtn_hombreActualizar.setSelected(true);
            }else if("Femenino".equalsIgnoreCase(genero)||"Female".equalsIgnoreCase(genero)){
                this.jrbtn_mujerActualizar.setSelected(true);
            }else if ("Otro".equalsIgnoreCase(genero)||"Other".equalsIgnoreCase(genero)) {
                this.jrbtn_otroActualizar.setSelected(true);
            }

            
        }else{
            JOptionPane.showMessageDialog(null,"Usuario no encontrado", "Busqueda Usuario",0);
            this.Jtxt_nombreActualizar.setText("");
            this.Jtxt_edadActualizar.setText("");
            this.jbg_genero.clearSelection();
            this.jtxt_buscarNombre.setText("");
        }


    }//GEN-LAST:event_jbtn_searchActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_UpdateUs().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Actualizar;
    private javax.swing.JButton Jbtn_Limpiar;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JTextField Jtxt_edadActualizar;
    private javax.swing.JTextField Jtxt_nombreActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.ButtonGroup jbg_genero;
    private javax.swing.JButton jbtn_search;
    private javax.swing.JRadioButton jrbtn_hombreActualizar;
    private javax.swing.JRadioButton jrbtn_mujerActualizar;
    private javax.swing.JRadioButton jrbtn_otroActualizar;
    private javax.swing.JTextField jtxt_buscarNombre;
    // End of variables declaration//GEN-END:variables
}
