/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesUser;

import Vista.Form_Opciones;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class Form_OpcionesUser extends javax.swing.JFrame {

    /**
     * Creates new form Form_OpcionesUser
     */
    public Form_OpcionesUser() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbtn_ActualizarUs = new javax.swing.JButton();
        Jbtn_EliminarUs = new javax.swing.JButton();
        Jbtn_ListarUs = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        Jbtn_ActualizarUs.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_ActualizarUs.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_ActualizarUs.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_ActualizarUs.setText("Update User");
        Jbtn_ActualizarUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ActualizarUsActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_ActualizarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 50));

        Jbtn_EliminarUs.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_EliminarUs.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_EliminarUs.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_EliminarUs.setText("Delete User");
        Jbtn_EliminarUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_EliminarUsActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_EliminarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 190, 50));

        Jbtn_ListarUs.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_ListarUs.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_ListarUs.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_ListarUs.setText("List User");
        Jbtn_ListarUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ListarUsActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_ListarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 190, 50));

        Jbtn_Volver.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Volver.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_Volver.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_ActualizarUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ActualizarUsActionPerformed
        Form_UpdateUs up = new Form_UpdateUs();
        up.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_ActualizarUsActionPerformed

    private void Jbtn_EliminarUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_EliminarUsActionPerformed
        Form_EliminarUs el = new Form_EliminarUs();
        el.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_EliminarUsActionPerformed

    private void Jbtn_ListarUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ListarUsActionPerformed
        Form_ListarUs lis = new Form_ListarUs();
        lis.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_ListarUsActionPerformed

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_Opciones op = new Form_Opciones();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_OpcionesUser().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_ActualizarUs;
    private javax.swing.JButton Jbtn_EliminarUs;
    private javax.swing.JButton Jbtn_ListarUs;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
