/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesUser;

import Controlador.Encuentro;
import Modelo.Usuario;
import Vista.Form_ElegirInicio;
import Vista.Form_SeleccionarHeroe;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_NuevoUs extends javax.swing.JFrame {

    /**
     * Creates new form Form_NuevoUs
     */
    private Usuario usuarioActual; //para guardar el usuario y no de null
    
    public Form_NuevoUs() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_genero = new javax.swing.ButtonGroup();
        jbg_heroe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_Nick = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_edad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jrbtn_hombre = new javax.swing.JRadioButton();
        jrbtn_mujer = new javax.swing.JRadioButton();
        jrbtn_otro = new javax.swing.JRadioButton();
        Jbtn_guardar = new javax.swing.JButton();
        Jbtn_Limpiar = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Gender:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 60, 30));

        jtxt_Nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_NickActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 370, 30));

        jLabel4.setText("Nick:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 60, 30));

        jtxt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_edadActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, 30));

        jLabel5.setText("Age:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, 30));

        jPanel4.setToolTipText("");
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbg_genero.add(jrbtn_hombre);
        jrbtn_hombre.setText("Male");

        jbg_genero.add(jrbtn_mujer);
        jrbtn_mujer.setText("Female");

        jbg_genero.add(jrbtn_otro);
        jrbtn_otro.setText("Other");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbtn_hombre)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_mujer)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_otro)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrbtn_hombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbtn_mujer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrbtn_otro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 210, 30));

        Jbtn_guardar.setText("Save");
        Jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        Jbtn_Limpiar.setText("Clear");
        Jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        jbtn_volver.setText("Return");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("New User");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUsuario.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_NickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_NickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_NickActionPerformed

    private void jtxt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_edadActionPerformed

    private void Jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarActionPerformed
        //guardar los datos del nuevo usuario ingresado
        String nombre = this.jtxt_Nick.getText();
        int edad;
        try {
            edad = Integer.parseInt(this.jtxt_edad.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"La debe debe ser un numero valido!","ERROR",JOptionPane.ERROR_MESSAGE);
            return; //detenerse si la edad es invalida
        }
        
        String genero = "";
        
        if (this.jrbtn_hombre.isSelected()) {
            genero = "Masculino";
        }else if (this.jrbtn_mujer.isSelected()) {
            genero = "Femenino";
        }else if (this.jrbtn_otro.isSelected()) {
            genero = "Otro";
        }
        
        //si el genero no quedo marcado e intentan guardar
        if (genero.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debe seleccionar un género","ERROR",JOptionPane.ERROR_MESSAGE);
            return; //detiene la ejecucion para que no se guarde con genero vacio
        }

        int puntaje = 0;
        
        Usuario usuario = new Usuario(nombre, genero, edad, puntaje);
        Encuentro encuentro = new Encuentro();
        if (encuentro.crearUsuario(usuario)) {
            Usuario usuarioCompleto = encuentro.buscarPorNombreUsuario(nombre); // recuperar la instancia completa de la bd
            if (usuarioCompleto != null) {
                JOptionPane.showMessageDialog(null,"Usuario Ingresado!","Ingresar Usuario", 1);
                Form_SeleccionarHeroe sh = new Form_SeleccionarHeroe(usuarioCompleto);
                sh.setVisible(true);
                this.dispose();
            }else{ // caso si es que se guardo pero no se encontro al buscar
                JOptionPane.showMessageDialog(null,"Usuario ingresado, pero no se pudo cargar","Error de carga", 0);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Usuario no Ingresado","Ingresar Usuario",0);
        }
    }//GEN-LAST:event_Jbtn_guardarActionPerformed

    private void Jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LimpiarActionPerformed
        this.jtxt_Nick.setText("");
        this.jtxt_edad.setText("");
        this.jrbtn_hombre.setSelected(false);
        this.jrbtn_mujer.setSelected(false);
        this.jrbtn_otro.setSelected(false); 
        this.jbg_genero.clearSelection();
        this.jbg_heroe.clearSelection();
        this.jtxt_Nick.requestFocus();
    }//GEN-LAST:event_Jbtn_LimpiarActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        // TODO add your handling code here:
        Form_ElegirInicio ei = new Form_ElegirInicio();
        ei.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_volverActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_NuevoUs().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Limpiar;
    private javax.swing.JButton Jbtn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.ButtonGroup jbg_genero;
    private javax.swing.ButtonGroup jbg_heroe;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JRadioButton jrbtn_hombre;
    private javax.swing.JRadioButton jrbtn_mujer;
    private javax.swing.JRadioButton jrbtn_otro;
    private javax.swing.JTextField jtxt_Nick;
    private javax.swing.JTextField jtxt_edad;
    // End of variables declaration//GEN-END:variables
}
