/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesPersonaje;

import Controlador.Encuentro;
import Modelo.Villano;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_UpdateV extends javax.swing.JFrame {

    /**
     * Creates new form Form_UpdateV
     */
    public Form_UpdateV() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_tipo = new javax.swing.ButtonGroup();
        jbg_nivel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_nombreVillano = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_ataqueEspecial = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jrbtn_villano = new javax.swing.JRadioButton();
        jrbtn_boss = new javax.swing.JRadioButton();
        Jbtn_Actualizar = new javax.swing.JButton();
        Jbtn_Limpiar = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbtn_buscarPorNombreVillano = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jrbtn_nivelUno = new javax.swing.JRadioButton();
        jrbtn_nivelDos = new javax.swing.JRadioButton();
        jrbtn_nivelTres = new javax.swing.JRadioButton();
        jtxt_buscarVillano = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 130, 30));
        getContentPane().add(jtxt_nombreVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 380, 30));

        jLabel3.setText("Name Villain:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 30));

        jLabel4.setText("Name Special Attack:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, 30));
        getContentPane().add(jtxt_ataqueEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 380, 30));

        jbg_tipo.add(jrbtn_villano);
        jrbtn_villano.setText("Villain");

        jbg_tipo.add(jrbtn_boss);
        jrbtn_boss.setText("Boss");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbtn_villano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtn_boss)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrbtn_villano, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jrbtn_boss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 30));

        Jbtn_Actualizar.setText("Update");
        Jbtn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        Jbtn_Limpiar.setText("Clear");
        Jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel5.setText("Search Villain:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, 30));

        jLabel6.setText("Difficulty:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 130, 30));

        jbtn_buscarPorNombreVillano.setText("Search");
        jbtn_buscarPorNombreVillano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarPorNombreVillanoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_buscarPorNombreVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, 30));

        jbg_nivel.add(jrbtn_nivelUno);
        jrbtn_nivelUno.setText("1");

        jbg_nivel.add(jrbtn_nivelDos);
        jrbtn_nivelDos.setText("2");

        jbg_nivel.add(jrbtn_nivelTres);
        jrbtn_nivelTres.setText("3");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jrbtn_nivelUno)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_nivelDos)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_nivelTres)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrbtn_nivelUno, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jrbtn_nivelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jrbtn_nivelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 140, 30));
        getContentPane().add(jtxt_buscarVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 380, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Update Villain");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVillano (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ActualizarActionPerformed

        String nombreActualizado = this.jtxt_nombreVillano.getText().trim();
        String nombreOriginal = this.jtxt_buscarVillano.getText().trim(); // El nombre que usamos para buscar
        String ataqueEspecial = this.jtxt_ataqueEspecial.getText().trim();

        // Determinar Nivel de Dificultad
        int nivelDificultad = 0;
        if (this.jrbtn_nivelUno.isSelected()) {
            nivelDificultad = 1;
        } else if (this.jrbtn_nivelDos.isSelected()) {
            nivelDificultad = 2;
        } else if (this.jrbtn_nivelTres.isSelected()) {
            nivelDificultad = 3;
        }

        // determinar si es Jefe
        boolean esJefe = this.jrbtn_boss.isSelected();

        // validacion 
        if (nombreActualizado.isEmpty() || ataqueEspecial.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre y el Ataque Especial no pueden estar vacíos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nivelDificultad == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Nivel de Dificultad.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // crear objeto Villano con los datos actualizados
        Villano villanoActualizado = new Villano();
        villanoActualizado.setNombre(nombreActualizado);
        villanoActualizado.setTextoATQespecial(ataqueEspecial);
        villanoActualizado.setIndiceDificultad(nivelDificultad);
        villanoActualizado.setEsJefe(esJefe);

        
        Encuentro encuentro = new Encuentro();

        // llamar al método de actualización (requiere el nombre original como referencia)
        if (encuentro.actualizarVillano(villanoActualizado, nombreOriginal)) {
            JOptionPane.showMessageDialog(null, "Villano " + nombreActualizado + " actualizado con éxito!", "Actualización exitosa!", JOptionPane.INFORMATION_MESSAGE);

            // limpiar campos después del éxito
            Jbtn_LimpiarActionPerformed(evt);

        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar el villano. Revisa la BD o si el nombre original existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Jbtn_ActualizarActionPerformed

    private void Jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LimpiarActionPerformed
        this.jtxt_nombreVillano.setText("");
        this.jtxt_ataqueEspecial.setText("");
        this.jtxt_buscarVillano.setText("");
        this.jrbtn_boss.setSelected(false);
        this.jrbtn_villano.setSelected(false);
        this.jrbtn_nivelUno.setSelected(false);
        this.jrbtn_nivelDos.setSelected(false);
        this.jrbtn_nivelTres.setSelected(false);
        this.jbg_nivel.clearSelection();
        this.jbg_tipo.clearSelection();
        this.jtxt_buscarVillano.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_LimpiarActionPerformed

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_OpcionesPj pj = new Form_OpcionesPj();
        pj.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

    private void jbtn_buscarPorNombreVillanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarPorNombreVillanoActionPerformed
        // obtener el nombre a buscar
        String nombre = this.jtxt_buscarVillano.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del villano a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.jtxt_buscarVillano.requestFocus();
            return;
        }

        Encuentro encuentro = new Encuentro();

        // buscar al Villano (asumiendo que los campos de actualización usan los mismos nombres que los de creación: jtxt_nombreVillano, jtxt_ataqueEspecial)
        Villano villano = encuentro.buscarPorNombreVillano(nombre);

        if (villano != null) {
            // rellenar los campos de actualización
            this.jtxt_nombreVillano.setText(villano.getNombre());
            this.jtxt_ataqueEspecial.setText(villano.getTextoATQespecial());

            // seleccionar Nivel de Dificultad (usando los jrbtn de nivel)
            int nivel = villano.getIndiceDificultad();
            switch (nivel) {
                case 1:
                    this.jrbtn_nivelUno.setSelected(true);
                    break;
                case 2:
                    this.jrbtn_nivelDos.setSelected(true);
                    break;
                case 3:
                    this.jrbtn_nivelTres.setSelected(true);
                    break;
                default:
                    this.jbg_nivel.clearSelection();
                    break;
            }

            // seleccionar Tipo (esJefe) (usando los jrbtn de tipo)
            boolean esJefe = villano.isEsJefe();
            if (esJefe) {
                this.jrbtn_boss.setSelected(true);
            } else {
                this.jrbtn_villano.setSelected(true);
            }

        } else {
            // mensaje de error y limpieza
            JOptionPane.showMessageDialog(null, "Villano no encontrado.", "Busqueda Villano", JOptionPane.INFORMATION_MESSAGE);

            this.jtxt_nombreVillano.setText("");
            this.jtxt_ataqueEspecial.setText("");
            this.jbg_nivel.clearSelection();
            this.jbg_tipo.clearSelection();
            this.jtxt_buscarVillano.requestFocus();
        }
    }//GEN-LAST:event_jbtn_buscarPorNombreVillanoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_UpdateV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_UpdateV().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Actualizar;
    private javax.swing.JButton Jbtn_Limpiar;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.ButtonGroup jbg_nivel;
    private javax.swing.ButtonGroup jbg_tipo;
    private javax.swing.JButton jbtn_buscarPorNombreVillano;
    private javax.swing.JRadioButton jrbtn_boss;
    private javax.swing.JRadioButton jrbtn_nivelDos;
    private javax.swing.JRadioButton jrbtn_nivelTres;
    private javax.swing.JRadioButton jrbtn_nivelUno;
    private javax.swing.JRadioButton jrbtn_villano;
    private javax.swing.JTextField jtxt_ataqueEspecial;
    private javax.swing.JTextField jtxt_buscarVillano;
    private javax.swing.JTextField jtxt_nombreVillano;
    // End of variables declaration//GEN-END:variables
}
