/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesPersonaje;

import Vista.Form_Opciones;
import javax.swing.ImageIcon;

/**
 *
 * @author Panky
 */
public class Form_OpcionesPj extends javax.swing.JFrame {

    /**
     * Creates new form Form_OpcionesPj
     */
    public Form_OpcionesPj() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Jbtn_NewV = new javax.swing.JButton();
        Jbtn_ListarV = new javax.swing.JButton();
        Jbtn_UpdateV = new javax.swing.JButton();
        Jbtn_DeleteV = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Villains");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        Jbtn_NewV.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_NewV.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_NewV.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_NewV.setText("New Villain");
        Jbtn_NewV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_NewVActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_NewV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, 50));

        Jbtn_ListarV.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_ListarV.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_ListarV.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_ListarV.setText("Villain List");
        Jbtn_ListarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ListarVActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_ListarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 200, 50));

        Jbtn_UpdateV.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_UpdateV.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_UpdateV.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_UpdateV.setText("Update Villain");
        Jbtn_UpdateV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_UpdateVActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_UpdateV, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 200, 50));

        Jbtn_DeleteV.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_DeleteV.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_DeleteV.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_DeleteV.setText("Delete Villain");
        Jbtn_DeleteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_DeleteVActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_DeleteV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, 50));

        Jbtn_Volver.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_Volver.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        Jbtn_Volver.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 110, 50));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loop (2).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_NewVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_NewVActionPerformed
        Form_NuevoV v = new Form_NuevoV();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_NewVActionPerformed

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_Opciones op = new Form_Opciones();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

    private void Jbtn_UpdateVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_UpdateVActionPerformed
        Form_UpdateV up = new Form_UpdateV();
        up.setVisible(true);
        this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_UpdateVActionPerformed

    private void Jbtn_DeleteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_DeleteVActionPerformed
        Form_EliminarV el = new Form_EliminarV();
        el.setVisible(true);
        this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_DeleteVActionPerformed

    private void Jbtn_ListarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ListarVActionPerformed
        Form_ListarV lV = new Form_ListarV();
        lV.setVisible(true);
        this.dispose();
       // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_ListarVActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_OpcionesPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_OpcionesPj().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_DeleteV;
    private javax.swing.JButton Jbtn_ListarV;
    private javax.swing.JButton Jbtn_NewV;
    private javax.swing.JButton Jbtn_UpdateV;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
