/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.OpcionesPersonaje;

import Controlador.Encuentro;
import Modelo.Villano;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Panky
 */
public class Form_NuevoV extends javax.swing.JFrame {

    /**
     * Creates new form Form_NuevoV
     */
    public Form_NuevoV() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setTitle("Batman Rogue");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_villano = new javax.swing.ButtonGroup();
        jbg_nivel = new javax.swing.ButtonGroup();
        Jbtn_Guardar = new javax.swing.JButton();
        Jbtn_Limpiar = new javax.swing.JButton();
        Jbtn_Volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_nombreVillano = new javax.swing.JTextField();
        jtxt_ataqueEspecial = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jrbtn_villano = new javax.swing.JRadioButton();
        jrbtn_boss = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jrbtn_nivelUno = new javax.swing.JRadioButton();
        jrbtn_nivelDos = new javax.swing.JRadioButton();
        jrbtn_nivelTres = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbtn_Guardar.setText("Save");
        Jbtn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        Jbtn_Limpiar.setText("Clear");
        Jbtn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        Jbtn_Volver.setText("Return");
        Jbtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel2.setText("Name Villan:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 130, 30));

        jLabel4.setText("Type:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, 30));

        jLabel3.setText("Name Special Attack:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 30));
        getContentPane().add(jtxt_nombreVillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 320, 30));
        getContentPane().add(jtxt_ataqueEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 320, 30));

        jbg_villano.add(jrbtn_villano);
        jrbtn_villano.setText("Villain");

        jbg_villano.add(jrbtn_boss);
        jrbtn_boss.setText("Boss");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbtn_villano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtn_boss)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrbtn_villano, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jrbtn_boss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 120, 30));

        jLabel5.setText("Difficulty:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 30));

        jbg_nivel.add(jrbtn_nivelUno);
        jrbtn_nivelUno.setText("1");

        jbg_nivel.add(jrbtn_nivelDos);
        jrbtn_nivelDos.setText("2");

        jbg_nivel.add(jrbtn_nivelTres);
        jrbtn_nivelTres.setText("3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jrbtn_nivelUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbtn_nivelDos)
                .addGap(12, 12, 12)
                .addComponent(jrbtn_nivelTres)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jrbtn_nivelUno, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jrbtn_nivelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jrbtn_nivelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 120, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("New Villain");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoVillano (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_GuardarActionPerformed
// recolección de datos del formulario (strings y booleano)
        String nombre = this.jtxt_nombreVillano.getText();
        String ataqueEspecial = this.jtxt_ataqueEspecial.getText();

        // determinación del nivel de dificultad (CORRECCIÓN CLAVE)
        int nivelDificultad;
        if (this.jrbtn_nivelUno.isSelected()) {
            nivelDificultad = 1;
        } else if (this.jrbtn_nivelDos.isSelected()) {
            nivelDificultad = 2;
        } else if (this.jrbtn_nivelTres.isSelected()) {
            nivelDificultad = 3;
        } else {
            //manejar el caso donde no se selecciona ningún nivel
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Nivel de Dificultad (1, 2, o 3).", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // verificación de campos obligatorios (Nombre)
        if (nombre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Nombre no puede estar vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.jtxt_nombreVillano.requestFocus();
            return;
        }

        // determinar si es Jefe (Boss) o Villano estándar
        boolean esJefe = this.jrbtn_boss.isSelected();

        // creacion del objeto Villano y asignación de valores por defecto
        Villano villano = new Villano();

        // atributos de la UI
        villano.setNombre(nombre);
        villano.setTextoATQespecial(ataqueEspecial);
        villano.setIndiceDificultad(nivelDificultad); //aca van los valores ingresados
        villano.setEsJefe(esJefe);

        // atributos con VALORES POR DEFECTO de un nuevo villano <------------------------------
        villano.setHp(20);
        villano.setHpMax(20);
        villano.setAtaque(3);
        villano.setDefensa(2);
        villano.setEspecial(5);
        villano.setInteligencia(1);
        villano.setCostoEspecial(1);
        villano.setGuardiaActiva(false);
        villano.setImagenPath("Villano_Default.png");

        // Llamar al controlador para guardar en la BD
        Encuentro encuentro = new Encuentro();

        if (encuentro.crearVillano(villano)) {
            JOptionPane.showMessageDialog(null, "Villano '" + nombre + "' creado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            Jbtn_LimpiarActionPerformed(null); // Limpiar campos
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar el Villano. Puede que el nombre ya exista o haya un fallo de BD.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Jbtn_GuardarActionPerformed

    private void Jbtn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LimpiarActionPerformed
        this.jtxt_nombreVillano.setText("");
        this.jtxt_ataqueEspecial.setText("");
        this.jrbtn_boss.setSelected(false);
        this.jrbtn_villano.setSelected(false);
        this.jrbtn_nivelUno.setSelected(false);
        this.jrbtn_nivelDos.setSelected(false);
        this.jrbtn_nivelTres.setSelected(false);
        this.jbg_nivel.clearSelection();
        this.jbg_villano.clearSelection();
        this.jtxt_nombreVillano.requestFocus();
    }//GEN-LAST:event_Jbtn_LimpiarActionPerformed

    private void Jbtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_VolverActionPerformed
        Form_OpcionesPj opP = new Form_OpcionesPj();
        opP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_VolverActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Form_NuevoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_NuevoV().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Guardar;
    private javax.swing.JButton Jbtn_Limpiar;
    private javax.swing.JButton Jbtn_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.ButtonGroup jbg_nivel;
    private javax.swing.ButtonGroup jbg_villano;
    private javax.swing.JRadioButton jrbtn_boss;
    private javax.swing.JRadioButton jrbtn_nivelDos;
    private javax.swing.JRadioButton jrbtn_nivelTres;
    private javax.swing.JRadioButton jrbtn_nivelUno;
    private javax.swing.JRadioButton jrbtn_villano;
    private javax.swing.JTextField jtxt_ataqueEspecial;
    private javax.swing.JTextField jtxt_nombreVillano;
    // End of variables declaration//GEN-END:variables
}
